// AUTO-GENERATED by scripts/generate-pricing.mjs — DO NOT EDIT.
// Source of truth: scripts/pricing.source.mjs (DECISIONS.md #1)

export type TierId = 'free' | 'solo' | 'solo_plus' | 'founder' | 'agency';

export interface PricingTier {
  id: TierId;
  label: string;
  priceUsd: number | null;
  priceInr: number | null;
  status: 'production' | 'preview';
}

export const PRICING_TIERS: PricingTier[] = [
  {
    "id": "free",
    "label": "Free",
    "priceUsd": 0,
    "priceInr": 0,
    "status": "production"
  },
  {
    "id": "solo",
    "label": "Solo",
    "priceUsd": 5,
    "priceInr": 399,
    "status": "production"
  },
  {
    "id": "solo_plus",
    "label": "Solo Plus",
    "priceUsd": 9,
    "priceInr": 699,
    "status": "production"
  },
  {
    "id": "founder",
    "label": "Founder",
    "priceUsd": 15,
    "priceInr": 1199,
    "status": "production"
  },
  {
    "id": "agency",
    "label": "Agency",
    "priceUsd": null,
    "priceInr": null,
    "status": "preview"
  }
];

export const TIER_LABELS: Record<TierId, string> = {
  "free": "Free",
  "solo": "Solo",
  "solo_plus": "Solo Plus",
  "founder": "Founder",
  "agency": "Agency"
};

export const TIER_PRICES: Record<TierId, number | null> = {
  "free": 0,
  "solo": 5,
  "solo_plus": 9,
  "founder": 15,
  "agency": null
};

export const TIER_PRICES_INR: Record<TierId, number | null> = {
  "free": 0,
  "solo": 399,
  "solo_plus": 699,
  "founder": 1199,
  "agency": null
};

export const BUYABLE_TIER_IDS: TierId[] = ["solo","solo_plus","founder"];
