#!/usr/bin/env node
// Generates `src/pricing.generated.ts` for each app from
// `scripts/pricing.source.mjs` (DECISIONS.md #1 / #5).
//
// Usage: node scripts/generate-pricing.mjs
// Run automatically as `pregenerate:pricing` / wired into each app's build.

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { PRICING_TIERS, BUYABLE_TIER_IDS } from './pricing.source.mjs';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const tierIds = PRICING_TIERS.map(t => `'${t.id}'`).join(' | ');

const banner = `// AUTO-GENERATED by scripts/generate-pricing.mjs — DO NOT EDIT.
// Source of truth: scripts/pricing.source.mjs (DECISIONS.md #1)
`;

const body = `
export type TierId = ${tierIds};

export interface PricingTier {
  id: TierId;
  label: string;
  priceUsd: number | null;
  status: 'production' | 'preview';
}

export const PRICING_TIERS: PricingTier[] = ${JSON.stringify(PRICING_TIERS, null, 2)};

export const TIER_LABELS: Record<TierId, string> = ${JSON.stringify(
  Object.fromEntries(PRICING_TIERS.map(t => [t.id, t.label])),
  null,
  2
)};

export const TIER_PRICES: Record<TierId, number | null> = ${JSON.stringify(
  Object.fromEntries(PRICING_TIERS.map(t => [t.id, t.priceUsd])),
  null,
  2
)};

export const BUYABLE_TIER_IDS: TierId[] = ${JSON.stringify(BUYABLE_TIER_IDS)};
`;

const out = banner + body;

const targets = [
  path.join(ROOT, 'Web-app', 'src', 'pricing.generated.ts'),
  path.join(ROOT, 'Desktop-app', 'src', 'pricing.generated.ts'),
];

for (const target of targets) {
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, out);
  console.log(`wrote ${path.relative(ROOT, target)}`);
}
